blueprint:
  name: View Assist - Device Functions
  description: Various device functions for the View Assist Satellites (View Assist devicefunctions v 1.0.0)
  domain: automation
  input:
    repeat_command:
      name: Repeat command
      description: The phrase you want to use to trigger repeating last spoken response
      default: "(what did you say  | [please] say that again [please] | [please] repeat that [please])"
    group_entity: 
      name: Group Entity
      description: The group entity that holds the list of ViewAssist devices
      selector:
        entity:
          filter:
            - domain: group
      default: "group.viewassist_satellites" 
trigger:
  - platform: conversation
    command:
      - !input repeat_command
    id: repeat
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - repeat
        sequence:
          - set_conversation_response: >-
              I said {{ state_attr(target_satellite_device, 'last_said')| replace("I said", "")}}
variables:
  group_entity: !input group_entity
  target_satellite_device: |-
    {% for sat in expand(group_entity) %}
      {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
        {{ sat.entity_id }}
      {% endif %}
    {% endfor %}
  target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
  target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
  target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type') }}"              
