blueprint:
  name: View Assist - Travel Times by Waze
  description: Get travel time estimates from Waze  (View Assist traveltimesbywaze v 1.0.0)
  domain: automation
  input:
    travelfromhome:
      name: Travel from home
      description: The phrase used to get directions from home
      default: "how long (does | will) it take to (go | drive) to {destination}"
    travelfromatob:
      name: Travel from point A to point B
      description: The phrase used to get directions from point A to point B
      default: "how long (does | will) it take to (go | drive) from {origin} to {destination}"
    traveltoafromb:
      name: Travel to point B from point A
      description: The phrase used to get directions to point B from point A
      default: "how long (does | will) it take to (go | drive) to {destination} from {origin}"
    home:
      name: Home
      description: The default starting point address
      default: "1600 Pennsylvania Avenue NW, Washington, DC 20500"
    places:
      name: Places
      description: A list of your favorite places with their addresses
      default: >-
        "places:
          home: 123 Main Street, Beverly Hills, CA 90210"
    region:
      name: Region
      description: Your Waze region
      selector:
        select:
          options:
            - us
            - na
            - eu
            - il
            - au    
      default: us      
    group_entity: 
      name: Group Entity
      description: The group entity that holds the list of ViewAssist devices
      selector:
        entity:
          filter:
            - domain: group
      default: "group.viewassist_satellites" 
trigger:
  - platform: conversation
    command: !input travelfromhome
    id: travelfromhome
  - platform: conversation
    command: 
      - !input travelfromatob
      - !input traveltoafromb
    id: travelfromatob    
condition: []
action:
  - variables:
      home: !input home
      region: !input region
      origin: "{{ trigger.slots.origin }}"
      destination: "{{ trigger.slots.destination }}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - travelfromhome
        sequence:
          - action: waze_travel_time.get_travel_times
            data:
              region: "{{ region }}"
              origin: "{{ home }}"
              destination: "{{ destination }}"
            response_variable: routes_response
          - set_conversation_response: >
              It will take about {% set time =
              routes_response['routes'][0]['duration'] | round %}{% if time > 60
              %}{% set hours = time // 60 %}{% set minutes = time % 60 %}{{
              hours }} hours and {{ minutes }} minutes{% else %}{{ time }}
              minutes{% endif %} to drive to {{ destination | title }}
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - travelfromatob
        sequence:
          - action: waze_travel_time.get_travel_times
            data:
              region: "{{ region }}"
              origin: "{{ origin }}"
              destination: "{{ destination }}"
            response_variable: routes_response
          - set_conversation_response: >
              It will take about {% set time =
              routes_response['routes'][0]['duration'] | round %}{% if time > 60
              %}{% set hours = time // 60 %}{% set minutes = time % 60 %}{{
              hours }} hours and {{ minutes }} minutes{% else %}{{ time }}
              minutes{% endif %} to drive from {{ origin | title }} to {{
              destination | title }}
            enabled: true
mode: single
