blueprint:
  name: View Assist - Thermostat Control
  description: Control thermostat temperature  (View Assist thermostatcontrol v 1.0.0)
  domain: automation
  increasetemperature:
    command:
      name: Command
      description: The phrase used to increase the current thermostat temperature set point
      default: "(increase thermostat | raise thermostat | increase temperature | raise temperature) {amount} (degree | degrees | °)"
    decreasetemperature:
      command:
        name: Command
        description: The phrase used to decrease the current thermostat temperature set point
        default: "(decrease thermostat | lower thermostat | decrease temperature | lower temperature) {amount} (degree| degrees | °)"
    setemperature:
      command:
        name: Command
        description: The phrase used to set the current thermostat temperature set point
        default: "(set thermostat | change thermostat | set temperature | change temperature) [to] {amount} [degree | degrees | °]"            
    thermostat:
      name: Thermostat device
      description: The thermostat device to control (example climate.livingroomtstat)
      selector:
        climate:
      default: ""      
    view:
      name: View
      description: The View Assist dashboard view to use for thermostat device
      default: "/dashboard-viewassist/thermostat"
    group_entity: 
      name: Group Entity
      description: The group entity that holds the list of ViewAssist devices
      selector:
        entity:
          filter:
            - domain: group
      default: "group.viewassist_satellites" 
trigger:
  - platform: conversation
    command: !input increasetemperature
    id: increasetemperature
  - platform: conversation
    command: !input decreasetemperature
    id: decreasetemperature
  - platform: conversation
    command: !input settemperature
    id: settemperature
condition: []
action:
  - variables:
      amount: "{{ trigger.slots.amount }}"
      thermostat: !input thermostat
      group_entity: !input group_entity
      view: !input view
      target_satellite_device: |-
        {% for sat in expand(group_entity) %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.entity_id }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type') }}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - increasetemperature
            enabled: true
        sequence:
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: cool
            then:
              - data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature')+ amount }} 
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: heat
            then:
              - data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') + amount }} 
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: heat_cool
            then:
              - data:
                  target_temp_high: >-
                    {{ state_attr(thermostat,'target_temp_high') + amount }}
                  target_temp_low: >-
                    {{ state_attr(thermostat,'target_temp_low') + amount }}
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - set_conversation_response: Thermostat temperature raised {{ amount }} degree
      - conditions:
          - condition: trigger
            id:
              - decreasetemperature
            enabled: true
        sequence:
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: cool
            then:
              - data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') - amount }} 
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: heat
            then:
              - data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') - amount }} 
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: heat_cool
            then:
              - data:
                  target_temp_high: >-
                    {{ state_attr(thermostat,'target_temp_high') - amount }}
                  target_temp_low: >-
                    {{ state_attr(thermostat,'target_temp_low') - amount }}
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - set_conversation_response: Thermostat temperature lowered {{ amount }} degree
      - conditions:
          - condition: trigger
            id:
              - settemperature
            enabled: true
        sequence:
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: cool
            then:
              - data:
                  temperature: "{{ amount }}"
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - if:
              - condition: state
                entity_id: "{{ thermostat }}"
                state: heat
            then:
              - data:
                  temperature: "{{ amount }}"
                target:
                  entity_id: "{{ thermostat }}"
                action: climate.set_temperature
            enabled: true
          - set_conversation_response: Thermostat temperature set to {{ amount }} degrees
    default: []
  - if:
      - condition: template
        value_template: "{{ target_satellite_device_type != 'audio_only' }}"
    then:
      - data:
          path: "{{ view }}"
        target:
          device_id: "{{target_display_device}}"
        action: browser_mod.navigate
mode: single
