# Currency Convertor
blueprint:
  name: View Assist - Currency Convertor
  description: Convert currency from one type to another (View Assist Currency Convertor v 0.2.0)
  domain: automation
  input:
    rapid_apikey:
      name: Rapid Api Key
      description: Your Rapid Api Key
      default: YOURAPIKEY
    group_entity:
      name: Group Entity
      description: The group that holds the list of View Assist satellites(example
        group.viewassist_satellites)
      selector:
        entity:
          filter:
          - domain:
            - group
          multiple: false
      default: group.viewassist_satellites
    view_path:
      name: Dashboard Info view
      description: The View Assist dashboard view to use for displaying information (example /dashboard-viewassist/info)
      default: /dashboard-viewassist/info
trigger:
  - platform: mqtt
    topic: viewassist/intent/currencyconvertor
condition: []
action:
  - variables:
      group_entity: !input group_entity
      rapidapikey: !input rapid_apikey
      view: !input view_path
      target_satellite_device: |-
        {% for sat in expand(group_entity) %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.entity_id }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type') }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['intent'] == 'exchange'}}"
        sequence:
          - action: pyscript.currencyconvertor
            data:
              rapidapikey: "{{ rapidapikey }}"
              currencyto: "{{ trigger.payload_json['tocurrency'] }}"
            response_variable: conversion_response
          - if:
              - condition: template
                value_template: "{{ conversion_response['error'] == 0 }}"
            then:
              - action: pyscript.response_handler
                data:
                  intent: ExchangeCurrency
                  response: speech
                  custom: viewassist-currencyconvertor
                  basecurrency: "{{ conversion_response['data']['from'] }}"
                  exchange: "{{ conversion_response['data']['value'] }}"
                  exchangecurrency: "{{ conversion_response['data']['to'] }}"
                response_variable: response_speech
              - set_conversation_response: "{{ response_speech['message'] }}"
              - if:
                  - condition: template
                    value_template: "{{ target_satellite_device_type != 'audio_only' }}"
                then:
                  - data:
                      entity_id: "{{ target_satellite_device }}"
                      title: Currency Convertor
                      message_font_size: 4vw
                      message: "{{ response_speech['message'] }}"
                    action: python_script.set_state
                  - data:
                      path: "{{ view }}"
                      target:
                        device_id: "{{target_display_device}}"
                    action: browser_mod.navigate
            else:
              - set_conversation_response: >-
                  Error {{ conversion_response['error'] }} Message {{
                  conversion_response['message'] }}
              - if:
                  - condition: template
                    value_template: "{{ target_satellite_device_type != 'audio_only' }}"
                then:
                  - data:
                      entity_id: "{{ target_satellite_device }}"
                      title: Currency Convertor
                      message_font_size: 4vw
                      message: >-
                        Error {{ conversion_response['error'] }} Message {{
                        conversion_response['message'] }}
                    action: python_script.set_state
                  - data:
                      path: "{{ view }}"
                      target:
                        device_id: "{{target_display_device}}"
                    action: browser_mod.navigate
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['intent'] == 'convert'}}"
        sequence:
          - action: pyscript.currencyconvertor
            data:
              rapidapikey: "{{ rapidapikey }}"
              currencyfrom: "{{ trigger.payload_json['fromcurrency'] }}"
              currencyto: "{{ trigger.payload_json['tocurrency'] }}"
            response_variable: conversion_response
          - if:
              - condition: template
                value_template: "{{ conversion_response['error'] == 0 }}"
            then:
              - action: pyscript.response_handler
                data:
                  intent: ConvertCurrency
                  response: speech
                  custom: viewassist-currencyconvertor
                  amount: "{{ conversion_response['data']['amount'] }}"
                  fromcurrency: "{{ conversion_response['data']['from'] }}"
                  convert: "{{ conversion_response['data']['value'] }}"
                  tocurrency: "{{ conversion_response['data']['to'] }}"
                response_variable: response_speech
              - set_conversation_response: "{{ response_speech['message'] }}"
              - if:
                  - condition: template
                    value_template: "{{ target_satellite_device_type != 'audio_only' }}"
                then:
                  - data:
                      entity_id: "{{ target_satellite_device }}"
                      title: Currency Convertor
                      message_font_size: 4vw
                      message: "{{ response_speech['message'] }}"
                    action: python_script.set_state
                  - data:
                      path: "{{ view }}"
                      target:
                        device_id: "{{target_display_device}}"
                    action: browser_mod.navigate
            else:
              - set_conversation_response: >-
                  Error {{ conversion_response['error'] }} Message {{
                  conversion_response['message'] }}
              - if:
                  - condition: template
                    value_template: "{{ target_satellite_device_type != 'audio_only' }}"
                then:
                  - data:
                      entity_id: "{{ target_satellite_device }}"
                      title: Currency Convertor
                      message_font_size: 4vw
                      message: >-
                        Error {{ conversion_response['error'] }} Message {{
                        conversion_response['message'] }}
                    action: python_script.set_state
                  - data:
                      path: "{{ view }}"
                      target:
                        device_id: "{{target_display_device}}"
                    action: browser_mod.navigate
mode: single


