alias: VIEW ASSIST - Set mode
description: ""
trigger:
  - platform: conversation
    command:
      - (set mode [to] {mode} | turn on {mode} mode)
  - platform: conversation
    command: Turn off do not disturb mode
    id: dndoff
condition: []
action:
  - if:
      - condition: template
        value_template: >-
          {{ (trigger.slots.mode in modes) or
          (trigger.slots.mode in ['do not disturb'])}}
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ trigger.slots.mode in modes }}
            sequence:
              - if:
                  - condition: template
                    value_template: >-
                      {% if target_satellite_device_type == 'audio_only'
                      %}true{% else %}false{% endif %}
                then:
                  - set_conversation_response: >-
                      Sorry.  {{ trigger.slots.mode }} is not a valid mode for
                      this device
                else:
                  - service: python_script.set_state
                    data:
                      entity_id: " {{ target_satellite_device }} "
                      mode: "{{ trigger.slots.mode }}"
                  - set_conversation_response: Setting mode to {{ trigger.slots.mode }}
                    enabled: true
          - conditions:
              - condition: template
                value_template: "{{ trigger.slots.mode == 'do not disturb' }}"
            sequence:
              - set_conversation_response: Do not disturb mode is now on
              - service: python_script.set_state
                data:
                  entity_id: " {{ target_satellite_device }} "
                  do_not_disturb: true
    else:
      - set_conversation_response: "Sorry.  {{ trigger.slots.mode }} is not a valid mode. "
  - choose:
      - conditions:
          - condition: trigger
            id:
              - dndoff
        sequence:
          - service: python_script.set_state
            data:
              entity_id: " {{ target_satellite_device }} "
              do_not_disturb: false
          - set_conversation_response: Do not disturb mode is now off
variables:
  modes: "['normal', 'night', 'hold', 'cycle']"
  target_satellite_device: |-
    {% for sat in expand('group.viewassist_satellites') %}
      {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
        {{ sat.entity_id }}
      {% endif %}
    {% endfor %}
  target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
  target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
mode: single
