name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '18'  # You can set it to '18' or '20' depending on compatibility with Docusaurus
      
      - name: Install dependencies
        run: |
          cd wiki
          npm install
      
      - name: Build Docusaurus site
        run: |
          cd wiki
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wiki/build
